
image_dir_path: "/path/to/images"

model:
  architecture: "resnet50"  # 'resnet50'/'vgg16'/'efficientnet_b0'/'vit_base_patch16_224'
  input_size: 224
  num_classes: 3
  weights_path: "NONE"

train:
  epochs: 30
  batch_size: 32
  num_workers: 1
  lr_scheduler: "StepLR"  # 'StepLR'/'ExponentialLR'/'ReduceLROnPlateau'/...
  lr_scheduler_params:
    step_size: 10
    gamma: 0.1
  optimizer: "Adam" # 'RMSprop'/'Adam'/'SGD'/...
  optimizer_params:
    lr: 0.001
  labels_table_path: "/path/to/training_data.xlsx"
  augmentations: ["random_rotate", "random_blur", "random_color_jitter"]

valid:
  batch_size: 32
  num_workers: 1
  labels_table_path: "/path/to/evaluation_data.xlsx"
  augmentations: ["random_rotate", "random_color_jitter"]
